### PR TITLE
Adding in more images and detail to the index page for Quacking Javascript

### PR DESCRIPTION
**Pull request by mickfuzz**
There are more changes to be made that I'll be doing over the weekend but I wanted to check I have the process right now. 

Thanks
Mick

### CODE REVIEW

**Comment by secretrobotron** [comment]
Hey @mickfuzz, it looks like there's something amiss about this PR. I cleaned it up a bit and pushed up your work to my own repo: https://github.com/secretrobotron/webmaker-curriculum/tree/gh-pages

Can you make sure the work you did is still represented here? http://secretrobotron.github.io/webmaker-curriculum/

**Comment by secretrobotron** [comment]
@mickfuzz if everything looks like it's as you left it, we can merge https://github.com/mozilla/webmaker-curriculum/pull/202 instead.

**Comment by secretrobotron** [comment]
cc @LauraHilliger

**Comment by LauraHilliger** [comment]
sent @mickfuzz an email to double check that everything is correct, but I merged your fix @secretrobotron and https://github.com/mozilla/webmaker-curriculum/pull/205 should have fixed all the things!!

**Pull request closed without merging**
