### PR TITLE
Webmaker (mobile) Activities for Maker Party

### PR DESCRIPTION
**Pull request by secretrobotron**
Real ones:
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/learning-about-the-internet.html
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/setting-up-your-phone.html
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/publishing-and-sharing.html
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/glossary.html
- http://mozilla.github.io/webmaker-curriculum/MobileWeb/facilitator-guide.html

---

Old ones:
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/learning-about-the-internet.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/setting-up-your-phone.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/publishing-and-sharing.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/glossary.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/facilitator-guide.html

### CODE REVIEW

**Comment by secretrobotron** [comment]
@thornet @amirad can you check this out and review? Should be available for preview at http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html soon.

**Comment by secretrobotron** [comment]
Thanks for your comments/suggestions @omnignorant. Would appreciate your feedback on the finished product as well.

**Comment by amirad** [comment]
@secretrobotron so this is different then the offline paper prototype activity? This seems like a blend of that and the webmaker activity.

**Comment by secretrobotron** [comment]
Several more pages now:
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/learning-about-the-internet.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/setting-up-your-phone.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/publishing-and-sharing.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/glossary.html
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/facilitator-guide.html

**Comment by secretrobotron** [comment]
@amirad nope. There are two activities in @LauraReynal's doc. I used the second one.

**Comment by chrislarry33** [comment]
Love this!!!!! thx...can you ping me when done @secretrobotron

**Comment by secretrobotron** [comment]
@chrislarry33 done!

One bit that's missing: web literacy competencies from the souktel and offline activities. Think you can help, @chrislarry33 @amirad @ldecoursy?

**Comment by secretrobotron** [comment]
- http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html

**Comment by amirad** [comment]
YAY! Thanks much @secretrobotron - drafted some feedback below:

http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html
*It's not clear where to send the participant profile form once people complete it?
*Can we add details on where they can find things like the Discover Gallery? 
*To the point above, it may be handy to actually include some screenshots of the app
*What is A4 paper? Can we just say paper?
*Should we include info on how Webmaker App has just launched and is still being updated on the activity? Might ease the frustration of those who run into bugs or issues. 

http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html
*What is A5 paper? Can we just say paper the size of cue cards? 
*Same question about the participant profile? Are you wanting to collect this? How does the facilitator use this info?
*"In some cultures participants might be shy" love that you're recognizing this but we might want to be softer on the language as this can be attributed to age, gender etc. Would recommend using "Sometimes participants might be shy to talk in front of a large audience....."
*I'm having trouble understanding how to use the A5 cards to create a story? Can we add more context there on how to use them as a story with the magazines/ropes. 
*"During the next hour, participants will make something on paper, in small groups, in pairs or individually." Let's add more context here. Revision suggestion "During the next hour, participants will layout their story on paper, in small groups, in pairs or individually." Should we be providing any more info on how to 'make' a story?

General feedback
*Can we switch up some of the pictures so they are not the same in both activities? I was confused because they look so similar!
*Should we take out all the idea generation parts of the Webmaker App activity and reference the offline activity for people to do first before creating their story? There seems to be some overlap and would help reduce the text overload in the Webmaker App activity. 

@HPaulJohnson @KevZawacki @ldecoursy @thornet @omnignorant would love if you can share any feedback as well. Goal is to update the site with these links and send these out to the greater community on Wednesday!

**Comment by ldecoursy** [comment]
Looking at the Design a Story activity: Do we want to include the participant profile in this activity for Maker Party? Or was more for development/testing? +1 to Amira's comment above about clarifying somewhere - perhaps in the Research Contribution Opportunity section - that this is a new app. Might also suggest this part is optional for those that want to provide feedback...

Also think Laura D has some pics of the collage/index card activity that might be useful to include here. Maybe just simple to swap the thumbnail pic with the one featured after the description of that activity (pink teddy bear) :)

**Comment by secretrobotron** [comment]
- Dropped the participant profile form thing. Not sure where to store that data. Should consult @LauraReynal when she's back. Happy to add it back in.
- Added a note about mentorship and encouraging participants to do their own workshop.
- Changed up the pictures a bit. They're non-trivial to source though. If you can find more suitable replacements, do suggest :) (drop links here!)
- Added a "keep in mind" section to tell people how to deal with bugs and feedback
- Clarified/augments paper size references
- Fixed up the narrative in the design one — should be a bit more clear of what to make now
- Added notes to the create activity about using the design activity in place of the sketch and ideation sections

**Comment by chrislarry33** [comment]
L-O-V-E the progress here, thanks for your work here @secretrobotron and for everyone who gave feedback. Don't wait for my input, dont want to slow it down. You all got this!

**Comment by secretrobotron** [comment]
thanks @adamlofting :yellow_heart: 

@amirad @ldecoursy @chrislarry33 landed!

**Comment by lauradereynal** [comment]
Hey everyone ! thanks for the great feedback and thanks @secretrobotron for putting this into pages ! 

Let me know if anything is needed from my side. 
The participant's profiles were just for research, not needed.

**Comment by chadsansing** [comment]
@hannahkane, @secretrobotron, @LauraReynal, @ldecoursy, @chrislarry33, @amirad:

Do we feel ready to frame these in a module landing page like [this](https://teach.mozilla.org/activities/web-lit-basics/) for /activities?

I'd suggest meta & sequencing like this (please suggest whatever changes need to be made esp. re: credits):

# Meta

**Title:** Read, Write, and Participate with Webmaker
**Level:** Beginner mobile users
**Developed by** [Bobby Richter](https://twitter.com/secretrobotron) and [Laura de Reynal](https://twitter.com/lau_nk) for [Mozilla Learning Networks](https://teach.mozilla.org)
**Brief description:** Learn how to set up your mobile device to write, publish, and share stories with the [Webmaker App](https://webmaker.org) from [Mozilla Learning Networks](https://teach.mozilla.org).
**Image:** http://mozilla.github.io/webmaker-curriculum/images/designing-webmaker.jpg

## Sequence

### Read

[Learning About the Internet](http://mozilla.github.io/webmaker-curriculum/MobileWeb/learning-about-the-internet.html)

### Write

[Setting Up Your Phone](http://mozilla.github.io/webmaker-curriculum/MobileWeb/setting-up-your-phone.html)
[Publishing and Sharing on the Internet](http://mozilla.github.io/webmaker-curriculum/MobileWeb/publishing-and-sharing.html)

### Participate

[Create a Webmaker Project](http://mozilla.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html)
[Design a Story for the Web](http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html)

**Comment by amirad** [comment]
Bolded some suggestions below. I was mainly trying to adjust the description so that people know the app is Android-based but they can also do the offline activities if they don't use the app. 

Title: Read, Write, and Participate **on mobile** with Webmaker
Level: Beginner mobile users
Developed by Bobby Richter and Laura de Reynal for Mozilla Learning Networks
Brief description: Learn how to set up your mobile device to write, publish, and share stories with the Webmaker **Android\* App** **and offline story-boarding.**
Image: http://mozilla.github.io/webmaker-curriculum/images/designing-webmaker.jpg

**Comment by hannahkane** [comment]
WFM.

To create the page itself, we'll need the following (to see how this will look, just look at https://teach.mozilla.org/activities/web-lit-basics/ as an example):
- Two-sentence description: Learn how to set up your mobile device to write, publish, and share stories with the Webmaker Android App and offline story-boarding.
- Image: http://mozilla.github.io/webmaker-curriculum/images/designing-webmaker.jpg
- Learning Objectives: [need something brief here]
- For each activity:
  - Title
  - "Understanding ________"
  - Brief description
  - Image

**Comment by chrislarry33** [comment]
Love the progress here, we will need to credit Suktel here as well

**Comment by chadsansing** [comment]
@hannahkane et al., how about...

**Learning Objectives**: Learners will understand how their mobile devices connect to the Web and then learn how to design, write, and publish personal and community stories through the Webmaker Android App.

Will next work up suggestions for the activities meta.

**Comment by chadsansing** [comment]
Hey, All - here's a first go at the activities' meta with suggested changes to images and WebLit tags in each activity's sidebar.

https://docs.google.com/a/mozilla.com/document/d/1FOEOjMlYc8iqtaDdmqAul-s8F37xGQaF8HqRU9RheDw/edit?usp=sharing

Please look at the meta and drop in any feedback by EOD today, 9/15/15.

+1 to Chris's reminder to credit Suktel, as well.

Thank you!

**Comment by chrislarry33** [comment]
WFM, thanks Chad. Keen to get these up

**Comment by chadsansing** [comment]
@hannahkane, can we add this:

[Remix this Webmaker Android App storytelling activity for your community with Thimble!](https://d157rqmxrxj6ey.cloudfront.net/rara/4349/)

to the bottom of

http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html

as per @secretrobotron's [suggestion](https://github.com/mozilla/webmaker-curriculum/issues/220)?

**Comment by secretrobotron** [comment]
@hannahkane @chadsansing is there a plan for curating and (re)publishing curriculum/activities contributors have given us? (e.g. like this one that was made in Thimble. Where else can we list it?)

**Comment by hannahkane** [comment]
OK, all the copy and images look good. I can file a ticket to create a page at /activities/webmaker that is linked to from /activities.

I don't actually know how to edit http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html. When I click on "view on github", it 404s. Does anyone know who created it in the first place?

@secretrobotron - I think Step 1 is figuring out a way for people like @chadsansing to easily view Thimble projects that people have made. Hence that email thread with Ashley. Will add Chad to that now.

**Comment by hannahkane** [comment]
Added ticket here: https://github.com/mozilla/teach.webmaker.org/issues/1264

**Pull request merged**
