### PR TITLE
Change content to match updated curriculum queue

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes issue https://github.com/mozilla/teach.mozilla.org/issues/1362

### CODE REVIEW

**Comment by hannahkane** [comment]
@mmmavis - can you review, please?

**Comment by hannahkane** [comment]
@mmmavis - I forgot about this one. When you have time, could you review this, please?

**Comment by mmmavis** [comment]
will do a quick scan today :dancer:

**Comment by mmmavis** [comment]
:+1: :tada: :tada: looking great! Thanks @hannahkane ! Just one note that tabs in code should be avoid or converted to spaces instead.  I will help you fix that in a follow up patch. :bowtie: Merging this now. Woohoooo!

**Comment by hannahkane** [comment]
ah, thanks, @mmmavis :)

**Pull request merged**
